### ISSUE TITLE
Panic on windows

### ISSUE THREAD

**Issue by AlexAkulov** [ShowMax/go-fqdn#1]
Hello!
I found that `host, err := net.LookupAddr("127.0.0.1")` on Windows can return empty array in host and nil in err.
That causes `panic: runtime error: index out of range` in 
https://github.com/ShowMax/go-fqdn/blob/master/fqdn.go#L32

It reproduce on go1.6.2 and go1.7

**Comment by zstyblik** [comment]
@AlexAkulov, thanks.
