### ISSUE TITLE
Adding the correct /etc/hosts configuration

### ISSUE THREAD

**Issue by chmike** [ShowMax/go-fqdn#6]
Could you please add in the README that to properly work on linux computers, the /etc/hosts should be configured as follow

    127.0.0.1 localhost
    1.2.3.4 host.domain.com host

where `1.2.3.4` is the IP address of the host, `host.domain.com` is the fully qualified domain name, and `host` the name of the host stripped of its domain name.

Without this, I got back useless values from your function. 

It would also be more idiomatic to call the function `Hostname` instead of `Get`.

**Comment by graywolf-at-work** [comment]
Well what this package does is just report canonical name based on `net.LookupAddr`, so documentation in hosts(5) applies.

I will take a look tomorrow and get back to you on this issue.

**Comment by graywolf-at-work** [comment]
I've landed new, improved version of this library and also improved the readme to mention hosts(5).
